from pathlib import Path

p = Path('logan-compiler/src/pipeline.rs')
s = p.read_text()

def rep(old, new, count=1):
    global s
    actual = s.count(old)
    assert actual == count, f'expected {count} occurrences, got {actual}: {old[:100]!r}'
    s = s.replace(old, new, count)

rep('use logan_ir::{\n    ContextConstraint,\n', 'use logan_ir::{\n    ContextConstraint, ParetoPlan,\n')
rep('''    /// Enter hardware-specialized planning. Candidate search lands in #82;\n    /// until then this is rejected rather than silently behaving like a fixed quant.\n    pub optimize: bool,\n    pub dry_run: bool,\n''', '''    /// Enter hardware-specialized Pareto planning.\n    pub optimize: bool,\n    /// Stable Pareto plan id or UX alias (`quality`, `balanced`, `long-context`, `latency`).\n    pub plan_choice: Option<String>,\n    /// Optional precomputed calibration-score JSON consumed by the optimizer.\n    pub calibration: Option<PathBuf>,\n    pub dry_run: bool,\n''')
rep('''            context: None,\n            optimize: false,\n            dry_run: false,\n''', '''            context: None,\n            optimize: false,\n            plan_choice: None,\n            calibration: None,\n            dry_run: false,\n''')
rep('''#[derive(Debug, Clone, Copy, PartialEq, Eq)]\nenum ExpertQuantization {\n    Exact,\n    Mxfp4,\n}\n''', '''#[derive(Debug, Clone, Copy, PartialEq, Eq)]\nenum ExpertQuantization {\n    Exact,\n    Mxfp4,\n}\n\n#[derive(Debug, Clone)]\nstruct ExpertQuantizationPlan {\n    default: ExpertQuantization,\n    by_layer: BTreeMap<u32, ExpertQuantization>,\n}\n\nimpl ExpertQuantizationPlan {\n    fn uniform(default: ExpertQuantization) -> Self {\n        Self {\n            default,\n            by_layer: BTreeMap::new(),\n        }\n    }\n\n    fn for_expert(&self, layer: u32) -> ExpertQuantization {\n        self.by_layer.get(&layer).copied().unwrap_or(self.default)\n    }\n}\n''')
rep('''pub struct DryRunSummary {\n    pub target_name: &'static str,\n    pub source_tensors: usize,\n    pub source_stored_bytes: u64,\n    pub plan: StoragePlan,\n}\n''', '''pub struct DryRunSummary {\n    pub target_name: &'static str,\n    pub source_tensors: usize,\n    pub source_stored_bytes: u64,\n    pub plan: StoragePlan,\n    pub optimizer_plans: Vec<ParetoPlan>,\n}\n''')
needle = '''fn resolve_expert_quantization(\n    request: &CompileRequest,\n    model: &SemanticModel,\n) -> Result<ExpertQuantization> {\n    match &request.quant {\n        QuantRequest::Exact => Ok(ExpertQuantization::Exact),\n        QuantRequest::Profile(profile) if profile == "mxfp4" => {\n            if model.architecture != Architecture::Qwen3_5MoeMoE {\n                return Err(ColicError::unsupported(\n                    Stage::TargetPlanning.as_str(),\n                    "`--quant mxfp4` currently supports Qwen3.5/3.6/3.7 MoE routed experts only",\n                ));\n            }\n            Ok(ExpertQuantization::Mxfp4)\n        }\n        QuantRequest::Profile(profile) => Err(ColicError::unsupported(\n            Stage::TargetPlanning.as_str(),\n            format!("quantization profile `{profile}` is not implemented"),\n        )),\n    }\n}\n'''
insert = needle + '''\nfn optimizer_quantization_plan(\n    request: &CompileRequest,\n    model: &SemanticModel,\n    target_profile: target::TargetProfile,\n    machine: &target::MachineProfile,\n    allow_default_selection: bool,\n) -> Result<(ExpertQuantizationPlan, Option<ParetoPlan>, Vec<ParetoPlan>)> {\n    if !request.optimize {\n        return Ok((\n            ExpertQuantizationPlan::uniform(resolve_expert_quantization(request, model)?),\n            None,\n            Vec::new(),\n        ));\n    }\n    let context = request.context.ok_or_else(|| {\n        ColicError::Usage("optimized compile requires --max-context or --require-context".into())\n    })?;\n    let optimization = crate::optimize::compile_plans(\n        model,\n        target_profile,\n        machine,\n        context,\n        request.calibration.as_deref(),\n        None,\n    )?;\n    let selected = match request.plan_choice.as_deref() {\n        Some(selector) => optimization.select(selector)?,\n        None if allow_default_selection => optimization.balanced_or_first()?,\n        None => {\n            return Err(ColicError::Usage(\n                "optimized compile requires --plan-choice NAME|ID in non-interactive code paths; run --dry-run to list plans".into(),\n            ));\n        }\n    };\n    let by_layer = crate::optimize::selected_layer_quantization(&selected)?\n        .into_iter()\n        .map(|(layer, mxfp4)| {\n            (\n                layer,\n                if mxfp4 {\n                    ExpertQuantization::Mxfp4\n                } else {\n                    ExpertQuantization::Exact\n                },\n            )\n        })\n        .collect();\n    Ok((\n        ExpertQuantizationPlan {\n            default: ExpertQuantization::Exact,\n            by_layer,\n        },\n        Some(selected),\n        optimization.plans,\n    ))\n}\n\npub fn preview_optimization(request: &CompileRequest) -> Result<Vec<ParetoPlan>> {\n    validate_supported_options(request)?;\n    if !request.optimize {\n        return Err(ColicError::Usage("optimization preview requires --optimize".into()));\n    }\n    let inventory = source::discover(&request.source)?;\n    let model = build_semantic_ir(&inventory)?.ok_or_else(|| {\n        ColicError::unsupported(\n            Stage::SemanticIr.as_str(),\n            "no supported architecture frontend matched this source model",\n        )\n    })?;\n    let machine = target::MachineProfile::probe();\n    let target_profile = target::resolve(&request.target, &machine)?;\n    let context = request.context.ok_or_else(|| {\n        ColicError::Usage("optimized compile requires --max-context or --require-context".into())\n    })?;\n    Ok(crate::optimize::compile_plans(\n        &model,\n        target_profile,\n        &machine,\n        context,\n        request.calibration.as_deref(),\n        None,\n    )?\n    .plans)\n}\n'''
rep(needle, insert)
old_dry = '''pub fn dry_run(request: &CompileRequest) -> Result<DryRunSummary> {\n    validate_supported_options(request)?;\n    let inventory = source::discover(&request.source)?;\n    let model = build_semantic_ir(&inventory)?.ok_or_else(|| {\n        ColicError::unsupported(\n            Stage::SemanticIr.as_str(),\n            "no supported architecture frontend matched this source model",\n        )\n    })?;\n    let quantization = resolve_expert_quantization(request, &model)?;\n    let target_profile = target::resolve(&request.target, &target::MachineProfile::probe())?;\n    let records = record_inventory(&model, quantization, target_profile)?;\n    let plan = storage::plan_records(&records, target_profile, 4 * 1024 * 1024 * 1024)?;\n    Ok(DryRunSummary {\n        target_name: target_profile.name,\n        source_tensors: inventory.tensors.len(),\n        source_stored_bytes: inventory.source_stored_bytes,\n        plan,\n    })\n}\n'''
new_dry = '''pub fn dry_run(request: &CompileRequest) -> Result<DryRunSummary> {\n    validate_supported_options(request)?;\n    let inventory = source::discover(&request.source)?;\n    let model = build_semantic_ir(&inventory)?.ok_or_else(|| {\n        ColicError::unsupported(\n            Stage::SemanticIr.as_str(),\n            "no supported architecture frontend matched this source model",\n        )\n    })?;\n    let machine = target::MachineProfile::probe();\n    let target_profile = target::resolve(&request.target, &machine)?;\n    let (quantization, _selected, optimizer_plans) =\n        optimizer_quantization_plan(request, &model, target_profile, &machine, true)?;\n    let records = record_inventory(&model, &quantization, target_profile)?;\n    let plan = storage::plan_records(&records, target_profile, 4 * 1024 * 1024 * 1024)?;\n    Ok(DryRunSummary {\n        target_name: target_profile.name,\n        source_tensors: inventory.tensors.len(),\n        source_stored_bytes: inventory.source_stored_bytes,\n        plan,\n        optimizer_plans,\n    })\n}\n'''
rep(old_dry, new_dry)
rep('''pub fn exact_record_inventory(model: &SemanticModel) -> Result<Vec<LoweredRecord>> {\n    record_inventory(\n        model,\n        ExpertQuantization::Exact,\n        target::LINUX_X86_64_AVX2_V1,\n    )\n}\n\nfn record_inventory(\n    model: &SemanticModel,\n    expert_quantization: ExpertQuantization,\n    target_profile: target::TargetProfile,\n) -> Result<Vec<LoweredRecord>> {\n''', '''pub fn exact_record_inventory(model: &SemanticModel) -> Result<Vec<LoweredRecord>> {\n    record_inventory(\n        model,\n        &ExpertQuantizationPlan::uniform(ExpertQuantization::Exact),\n        target::LINUX_X86_64_AVX2_V1,\n    )\n}\n\nfn record_inventory(\n    model: &SemanticModel,\n    expert_quantization: &ExpertQuantizationPlan,\n    target_profile: target::TargetProfile,\n) -> Result<Vec<LoweredRecord>> {\n''')
rep('''    for expert in model.routed_experts.values() {\n        let (stored_bytes, decoded_bytes) = if target_profile == target::MACOS_ARM64_METAL_APPLE8_V1\n        {\n            match expert_quantization {\n''', '''    for expert in model.routed_experts.values() {\n        let expert_quantization = expert_quantization.for_expert(expert.layer);\n        let (stored_bytes, decoded_bytes) = if target_profile == target::MACOS_ARM64_METAL_APPLE8_V1\n        {\n            match expert_quantization {\n''')
rep('''fn exact_sources(\n    model: &SemanticModel,\n    expert_quantization: ExpertQuantization,\n) -> Vec<ExactSource> {\n''', '''fn exact_sources(\n    model: &SemanticModel,\n    expert_quantization: &ExpertQuantizationPlan,\n) -> Vec<ExactSource> {\n''')
rep('''.map(|expert| ExactSource::Expert {\n                expert: Box::new(expert),\n                quantization: expert_quantization,\n            }),\n''', '''.map(|expert| {\n                let quantization = expert_quantization.for_expert(expert.layer);\n                ExactSource::Expert {\n                    expert: Box::new(expert),\n                    quantization,\n                }\n            }),\n''')
rep('''fn dense_quant_kind(dtype: &str) -> &'static str {\n    match dtype {\n        "BF16" => KIND_BF16,\n        "F32" => "f32",\n        "F8_E4M3FN" => "f8-e4m3",\n        _ => KIND_EXACT,\n    }\n}\n''', '''fn dense_quant_kind(dtype: &str) -> &'static str {\n    match dtype {\n        "BF16" => KIND_BF16,\n        "F32" => "f32",\n        "F8_E4M3FN" => "f8-e4m3",\n        _ => KIND_EXACT,\n    }\n}\n\nfn exact_expert_quant_kind(expert: &crate::ir::RoutedExpert) -> &'static str {\n    let matrices = [&expert.gate, &expert.up, &expert.down];\n    if matrices.iter().all(|matrix| {\n        matrix.source.dtype == "I8"\n            && matrix.scale.as_ref().is_some_and(|scale| {\n                matches!(scale.dtype.as_str(), "F8_E8M0" | "F8_E8M0FNU")\n            })\n    }) {\n        "mxfp4"\n    } else if matrices\n        .iter()\n        .all(|matrix| matrix.source.dtype == "BF16" && matrix.scale.is_none())\n    {\n        KIND_BF16\n    } else {\n        KIND_EXACT\n    }\n}\n''')
rep('''fn build_physical_plan(\n    sources: &[ExactSource],\n    records: &[LoweredRecord],\n    expert_quantization: ExpertQuantization,\n    target: target::TargetProfile,\n    quant_floor: QuantFloor,\n    machine: &target::MachineProfile,\n    package_fingerprint: &str,\n) -> Result<PlanArtifact> {\n''', '''fn build_physical_plan(\n    sources: &[ExactSource],\n    records: &[LoweredRecord],\n    target: target::TargetProfile,\n    quant_floor: QuantFloor,\n    machine: &target::MachineProfile,\n    package_fingerprint: &str,\n    optimizer: Option<&ParetoPlan>,\n) -> Result<PlanArtifact> {\n''')
rep('''    let mut placement = Vec::with_capacity(records.len());\n    let mut quant = Vec::with_capacity(records.len());\n''', '''    let mut placement = Vec::with_capacity(records.len());\n    let mut quant = Vec::with_capacity(records.len());\n    let mut layout = Vec::with_capacity(records.len());\n''')
old_arm = '''            ExactSource::Expert { expert, .. } => {\n                let stored_verified = if target == target::MACOS_ARM64_METAL_APPLE8_V1 {\n                    target::apple8_expert_stored_bytes(expert)?\n                } else {\n                    mxfp4_record::stored_bytes(expert)?\n                };\n                if record.stored_bytes != stored_verified {\n                    return Err(ColicError::Usage(format!(\n                        "Apple8 expert record {} planned {} bytes but the verified tile math says {stored_verified}",\n                        record.id, record.stored_bytes\n                    )));\n                }\n                largest_expert_decoded = largest_expert_decoded.max(record.decoded_bytes);\n                (\n                    format!("layers.{}.ffn.experts.{}", expert.layer, expert.expert),\n                    i32::try_from(expert.layer).map_err(|_| {\n                        ColicError::Usage("expert layer exceeds i32".into())\n                    })?,\n                    i32::try_from(expert.expert).map_err(|_| {\n                        ColicError::Usage("expert id exceeds i32".into())\n                    })?,\n                    if target == target::MACOS_ARM64_METAL_APPLE8_V1 {\n                        KIND_APPLE8\n                    } else {\n                        "mxfp4"\n                    },\n                    vec![3, u64::from(expert.gate.rows), u64::from(expert.gate.columns)],\n                )\n            }\n'''
new_arm = '''            ExactSource::Expert {\n                expert,\n                quantization,\n            } => {\n                let stored_verified = if target == target::MACOS_ARM64_METAL_APPLE8_V1 {\n                    target::apple8_expert_stored_bytes(expert)?\n                } else {\n                    match quantization {\n                        ExpertQuantization::Exact => target::exact_expert_stored_bytes(expert)?,\n                        ExpertQuantization::Mxfp4 => mxfp4_record::stored_bytes(expert)?,\n                    }\n                };\n                if record.stored_bytes != stored_verified {\n                    return Err(ColicError::Usage(format!(\n                        "expert record {} planned {} bytes but selected representation requires {stored_verified}",\n                        record.id, record.stored_bytes\n                    )));\n                }\n                largest_expert_decoded = largest_expert_decoded.max(record.decoded_bytes);\n                let dtype = if target == target::MACOS_ARM64_METAL_APPLE8_V1 {\n                    KIND_APPLE8\n                } else {\n                    match quantization {\n                        ExpertQuantization::Exact => exact_expert_quant_kind(expert),\n                        ExpertQuantization::Mxfp4 => "mxfp4",\n                    }\n                };\n                (\n                    format!("layers.{}.ffn.experts.{}", expert.layer, expert.expert),\n                    i32::try_from(expert.layer).map_err(|_| {\n                        ColicError::Usage("expert layer exceeds i32".into())\n                    })?,\n                    i32::try_from(expert.expert).map_err(|_| {\n                        ColicError::Usage("expert id exceeds i32".into())\n                    })?,\n                    dtype,\n                    vec![3, u64::from(expert.gate.rows), u64::from(expert.gate.columns)],\n                )\n            }\n'''
rep(old_arm, new_arm)
old_kind = '''        let kind = match source {\n            ExactSource::Expert { .. } => {\n                if target == target::MACOS_ARM64_METAL_APPLE8_V1 {\n                    KIND_APPLE8\n                } else {\n                    match expert_quantization {\n                        ExpertQuantization::Exact => KIND_EXACT,\n                        ExpertQuantization::Mxfp4 => "mxfp4",\n                    }\n                }\n            }\n            ExactSource::Tensor { .. } => dtype,\n        };\n'''
rep(old_kind, '        let kind = dtype;\n')
rep('''        placement.push((name.clone(), placed));\n        quant.push((\n''', '''        placement.push((name.clone(), placed));\n        layout.push((\n            name.clone(),\n            if matches!(source, ExactSource::Expert { .. })\n                && target == target::MACOS_ARM64_METAL_APPLE8_V1\n            {\n                crate::target_registry::APPLE8_MXFP4_TILE_LAYOUT\n            } else {\n                0\n            },\n        ));\n        quant.push((\n''')
old_pool = '''    let pool = check_uma_pool(\n        machine,\n        resident_bytes,\n        expert_cache_slots()\n            .checked_mul(largest_expert_decoded)\n            .unwrap_or(u64::MAX),\n    )?;\n    let memory = MemoryPlan {\n        placement,\n        quant,\n        ram_budget_bytes: pool,\n    };\n    Ok(PlanArtifact::new(package_fingerprint.to_string(), graph, memory))\n}\n'''
new_pool = '''    let pool = if let Some(optimizer) = optimizer {\n        let pool = machine\n            .ram_bytes\n            .unwrap_or(target::machine::DEFAULT_POOL_BUDGET);\n        if optimizer.metrics.resident_bytes > pool {\n            return Err(ColicError::unsupported(\n                Stage::StoragePlanning.as_str(),\n                format!(\n                    "selected optimizer plan needs {} resident bytes but the machine budget is {pool}",\n                    optimizer.metrics.resident_bytes\n                ),\n            ));\n        }\n        pool\n    } else {\n        check_uma_pool(\n            machine,\n            resident_bytes,\n            expert_cache_slots()\n                .checked_mul(largest_expert_decoded)\n                .unwrap_or(u64::MAX),\n        )?\n    };\n    let memory = MemoryPlan {\n        placement,\n        quant,\n        layout,\n        ram_budget_bytes: pool,\n    };\n    let artifact = PlanArtifact::new(package_fingerprint.to_string(), graph, memory);\n    Ok(match optimizer {\n        Some(optimizer) => artifact.with_optimizer(optimizer.clone()),\n        None => artifact,\n    })\n}\n'''
rep(old_pool, new_pool)
rep('''    let expert_quantization = resolve_expert_quantization(request, &model)?;\n    progress.stage(Stage::TargetPlanning);\n    let machine = target::MachineProfile::probe();\n    let target_profile = target::resolve(&request.target, &machine)?;\n''', '''    progress.stage(Stage::TargetPlanning);\n    let machine = target::MachineProfile::probe();\n    let target_profile = target::resolve(&request.target, &machine)?;\n    let (expert_quantization, selected_optimizer, _optimizer_plans) =\n        optimizer_quantization_plan(request, &model, target_profile, &machine, false)?;\n''')
rep('''    let sources = exact_sources(&model, expert_quantization);\n    let records = record_inventory(&model, expert_quantization, target_profile)?;\n''', '''    let sources = exact_sources(&model, &expert_quantization);\n    let records = record_inventory(&model, &expert_quantization, target_profile)?;\n''')
rep('''        let plan = build_physical_plan(\n            &sources,\n            &records,\n            expert_quantization,\n            target_profile,\n            request.quant_floor,\n            &machine,\n            &inventory.source_fingerprint,\n        )?;\n''', '''        let plan = build_physical_plan(\n            &sources,\n            &records,\n            target_profile,\n            request.quant_floor,\n            &machine,\n            &inventory.source_fingerprint,\n            selected_optimizer.as_ref(),\n        )?;\n''')
old_validate = '''fn validate_supported_options(request: &CompileRequest) -> Result<()> {\n    if request.optimize {\n        return Err(ColicError::unsupported(\n            Stage::TargetPlanning.as_str(),\n            "--optimize is wired to the shared context contract, but mixed-representation Pareto search is not implemented yet (see #82); refusing to pretend a fixed quant is optimized",\n        ));\n    }\n    match &request.quant {\n'''
new_validate = '''fn validate_supported_options(request: &CompileRequest) -> Result<()> {\n    if request.optimize {\n        if request.context.is_none() {\n            return Err(ColicError::Usage(\n                "optimized compile requires --max-context or --require-context".into(),\n            ));\n        }\n        if !matches!(request.quant, QuantRequest::Exact) {\n            return Err(ColicError::Usage(\n                "--optimize owns routed-expert representation selection; do not combine it with a global non-exact --quant profile".into(),\n            ));\n        }\n    } else {\n        if request.plan_choice.is_some() {\n            return Err(ColicError::Usage(\n                "--plan-choice requires --optimize".into(),\n            ));\n        }\n        if request.calibration.is_some() {\n            return Err(ColicError::Usage(\n                "--calibration requires --optimize".into(),\n            ));\n        }\n    }\n    match &request.quant {\n'''
rep(old_validate, new_validate)
p.write_text(s)
print('patched pipeline.rs')
