#!/usr/bin/env python3
import argparse
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "abi" / "coli-target-registry.toml"
C_OUT = ROOT / "c" / "generated" / "coli_target_registry.h"
RUST_OUT = ROOT / "logan-abi" / "src" / "generated" / "target_registry.rs"


def load():
    data = tomllib.loads(SOURCE.read_text())
    if data.get("schema") != 1:
        raise SystemExit("unsupported target registry schema")
    layouts = data["layouts"]
    profiles = data["profiles"]
    apple = profiles["macos_arm64_metal_apple8_v1"]
    tile = layouts["apple_mxfp4_tile8x32_v1"]
    if apple["allowed_layouts"] != [tile["id"]]:
        raise SystemExit("apple8-v1 must allow exactly the production tile layout")
    weight_row_bytes = tile["tile_columns"] // 2
    weight_bytes = tile["tile_rows"] * weight_row_bytes
    scale_bytes = tile["tile_rows"]
    if tile["tile_columns"] % 2 or tile["tile_bytes"] != weight_bytes + scale_bytes:
        raise SystemExit("Apple8 tile byte geometry is inconsistent")
    if tile["matrix_alignment"] <= 0 or tile["matrix_alignment"] & (tile["matrix_alignment"] - 1):
        raise SystemExit("Apple8 matrix alignment must be a power of two")
    names = [profile["name"] for profile in profiles.values()]
    ids = [profile["profile_id"] for profile in profiles.values()]
    layout_ids = [layout["id"] for layout in layouts.values()]
    if len(set(names)) != len(names) or len(set(ids)) != len(ids) or len(set(layout_ids)) != len(layout_ids):
        raise SystemExit("target registry contains duplicate names or IDs")
    return profiles, layouts


def c_text(profiles, layouts):
    portable = profiles["portable_v1"]
    apple = profiles["macos_arm64_metal_apple8_v1"]
    linux = profiles["linux_x86_64_avx2_v1"]
    tile = layouts["apple_mxfp4_tile8x32_v1"]
    row_bytes = tile["tile_columns"] // 2
    weight_bytes = tile["tile_rows"] * row_bytes
    scale_bytes = tile["tile_rows"]
    return f'''/* GENERATED by tools/gen_target_registry.py. DO NOT EDIT. */
#ifndef COLI_GENERATED_TARGET_REGISTRY_H
#define COLI_GENERATED_TARGET_REGISTRY_H

#include <stdint.h>

#define COLI_TARGET_PROFILE_PORTABLE_V1 "{portable["name"]}"
#define COLI_TARGET_PROFILE_MACOS_ARM64_METAL_APPLE8_V1 "{apple["name"]}"
#define COLI_TARGET_PROFILE_LINUX_X86_64_AVX2_V1 "{linux["name"]}"

#define COLI_TARGET_PROFILE_ID_MACOS_ARM64_METAL_APPLE8_V1 {apple["profile_id"]}u
#define COLI_TARGET_PROFILE_ABI_APPLE8_V1 {apple["target_profile_abi"]}u
#define COLI_EXECUTION_LAYOUT_ABI_APPLE8_V1 {apple["execution_layout_abi"]}u
#define COLI_KERNEL_ABI_APPLE8_MXFP4_TILE_V1 {apple["kernel_abi"]}u
#define COLI_TARGET_CLASS_APPLE8_METAL_V1 0x{apple["target_class"]:08x}u
#define COLI_LAYOUT_APPLE_MXFP4_TILE8X32_V1 0x{tile["id"]:04x}u

#define COLI_APPLE8_MXFP4_MATH_FORMAT 0x{tile["math_format"]:04x}u
#define COLI_APPLE8_MXFP4_SCALE_FORMAT 0x{tile["scale_format"]:04x}u
#define COLI_APPLE8_MXFP4_SCALE_BLOCK_ROWS {tile["scale_block_rows"]}u
#define COLI_APPLE8_MXFP4_SCALE_BLOCK_COLUMNS {tile["scale_block_columns"]}u
#define COLI_APPLE8_MXFP4_GROUP_SIZE {tile["group_size"]}u
#define COLI_APPLE8_MXFP4_MATRIX_ALIGNMENT {tile["matrix_alignment"]}u
#define COLI_APPLE8_MXFP4_TILE_ROWS {tile["tile_rows"]}u
#define COLI_APPLE8_MXFP4_TILE_COLUMNS {tile["tile_columns"]}u
#define COLI_APPLE8_MXFP4_WEIGHT_ROW_BYTES {row_bytes}u
#define COLI_APPLE8_MXFP4_WEIGHT_BYTES {weight_bytes}u
#define COLI_APPLE8_MXFP4_SCALE_BYTES {scale_bytes}u
#define COLI_APPLE8_MXFP4_TILE_BYTES {tile["tile_bytes"]}u

#define COLI_APPLE8_TARGET_OS {apple["target_os"]}u
#define COLI_APPLE8_TARGET_ARCH {apple["target_arch"]}u
#define COLI_APPLE8_TARGET_BACKEND {apple["backend_id"]}u
#define COLI_APPLE8_GPU_KIND {apple["gpu_kind"]}u
#define COLI_APPLE8_CPU_FEATURE_MASK UINT64_C(0x{apple["cpu_feature_mask"]:016x})
#define COLI_APPLE8_GPU_FAMILY_MIN {apple["gpu_family_min"]}u
#define COLI_APPLE8_REQUIRED_RUNTIME_FEATURES UINT64_C(0x{apple["required_runtime_features"]:016x})
#define COLI_APPLE8_RECORD_ALIGNMENT {apple["record_alignment"]}u
#define COLI_APPLE8_IO_GRANULARITY {apple["io_granularity"]}u
#define COLI_APPLE8_RESIDENT_ALIGNMENT {apple["resident_alignment"]}u
#define COLI_APPLE8_COMPILER_EMISSION_SUPPORTED {1 if apple["compiler_emission_supported"] else 0}u

#endif
'''


def rust_profile(name, p):
    allowed = ", ".join(f"0x{x:04x}" for x in p["allowed_layouts"])
    ident = name.upper()
    return f'''pub const {ident}_ALLOWED_LAYOUTS: &[u16] = &[{allowed}];
pub const {ident}: TargetProfileSpec = TargetProfileSpec {{
    name: "{p["name"]}", profile_id: {p["profile_id"]}, target_profile_abi: {p["target_profile_abi"]},
    execution_layout_abi: {p["execution_layout_abi"]}, kernel_abi: {p["kernel_abi"]}, target_class: 0x{p["target_class"]:08x},
    compiler_emission_supported: {str(p["compiler_emission_supported"]).lower()}, operating_system: "{p["operating_system"]}",
    architecture: "{p["architecture"]}", backend: "{p["backend"]}", record_alignment: {p["record_alignment"]},
    io_granularity: {p["io_granularity"]}, resident_alignment: {p["resident_alignment"]}, allowed_layouts: {ident}_ALLOWED_LAYOUTS,
}};
'''


def rust_text(profiles, layouts):
    apple = profiles["macos_arm64_metal_apple8_v1"]
    tile = layouts["apple_mxfp4_tile8x32_v1"]
    row_bytes = tile["tile_columns"] // 2
    weight_bytes = tile["tile_rows"] * row_bytes
    scale_bytes = tile["tile_rows"]
    profile_defs = "\n".join(rust_profile(name, profile) for name, profile in profiles.items())
    return f'''//! GENERATED by tools/gen_target_registry.py. DO NOT EDIT.
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TargetProfileSpec {{
    pub name: &'static str, pub profile_id: u32, pub target_profile_abi: u32,
    pub execution_layout_abi: u32, pub kernel_abi: u32, pub target_class: u32,
    pub compiler_emission_supported: bool, pub operating_system: &'static str,
    pub architecture: &'static str, pub backend: &'static str, pub record_alignment: u64,
    pub io_granularity: u64, pub resident_alignment: u64, pub allowed_layouts: &'static [u16],
}}

{profile_defs}
pub const PROFILES: &[TargetProfileSpec] = &[PORTABLE_V1, MACOS_ARM64_METAL_APPLE8_V1, LINUX_X86_64_AVX2_V1];

pub const APPLE8_PROFILE_NAME: &str = MACOS_ARM64_METAL_APPLE8_V1.name;
pub const APPLE8_PROFILE_ID: u32 = MACOS_ARM64_METAL_APPLE8_V1.profile_id;
pub const APPLE8_TARGET_PROFILE_ABI: u32 = MACOS_ARM64_METAL_APPLE8_V1.target_profile_abi;
pub const APPLE8_EXECUTION_LAYOUT_ABI: u32 = MACOS_ARM64_METAL_APPLE8_V1.execution_layout_abi;
pub const APPLE8_KERNEL_ABI: u32 = MACOS_ARM64_METAL_APPLE8_V1.kernel_abi;
pub const APPLE8_TARGET_CLASS: u32 = MACOS_ARM64_METAL_APPLE8_V1.target_class;
pub const APPLE8_COMPILER_EMISSION_SUPPORTED: bool = MACOS_ARM64_METAL_APPLE8_V1.compiler_emission_supported;
pub const APPLE8_MXFP4_TILE_LAYOUT: u16 = 0x{tile["id"]:04x};
pub const APPLE8_MXFP4_MATH_FORMAT: u16 = 0x{tile["math_format"]:04x};
pub const APPLE8_MXFP4_SCALE_FORMAT: u16 = 0x{tile["scale_format"]:04x};
pub const APPLE8_MXFP4_SCALE_BLOCK_ROWS: u32 = {tile["scale_block_rows"]};
pub const APPLE8_MXFP4_SCALE_BLOCK_COLUMNS: u32 = {tile["scale_block_columns"]};
pub const APPLE8_MXFP4_GROUP_SIZE: u32 = {tile["group_size"]};
pub const APPLE8_MXFP4_MATRIX_ALIGNMENT: u64 = {tile["matrix_alignment"]};
pub const APPLE8_MXFP4_TILE_ROWS: u64 = {tile["tile_rows"]};
pub const APPLE8_MXFP4_TILE_COLUMNS: u64 = {tile["tile_columns"]};
pub const APPLE8_MXFP4_WEIGHT_ROW_BYTES: u64 = {row_bytes};
pub const APPLE8_MXFP4_WEIGHT_BYTES: u64 = {weight_bytes};
pub const APPLE8_MXFP4_SCALE_BYTES: u64 = {scale_bytes};
pub const APPLE8_MXFP4_TILE_BYTES: u64 = {tile["tile_bytes"]};

pub fn profile_by_name(name: &str) -> Option<&'static TargetProfileSpec> {{ PROFILES.iter().find(|p| p.name == name) }}
pub fn layout_registered(layout: u16) -> bool {{ layout == 0 || layout == APPLE8_MXFP4_TILE_LAYOUT }}
pub fn profile_allows_layout(profile: &TargetProfileSpec, layout: u16) -> bool {{ profile.allowed_layouts.contains(&layout) }}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    profiles, layouts = load()
    # The C header output only exists when the C reference tree is present
    # (the standalone Logan repo has no c/ — the C fork is the oracle).
    outputs = [(RUST_OUT, rust_text(profiles, layouts))]
    if (ROOT / "c").is_dir():
        outputs.insert(0, (C_OUT, c_text(profiles, layouts)))
    if args.check:
        bad = [str(path.relative_to(ROOT)) for path, text in outputs if not path.exists() or path.read_text() != text]
        if bad:
            raise SystemExit("generated target registry is stale: " + ", ".join(bad))
        return
    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


if __name__ == "__main__":
    main()
