#!/usr/bin/env python3
from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    n = text.count(old)
    if n != 1:
        raise SystemExit(f"{path}: expected one match, found {n}: {old[:100]!r}")
    p.write_text(text.replace(old, new, 1))

# pipeline.rs: shared typed context + fail-closed optimizer entrypoint.
replace_once("logan-compiler/src/pipeline.rs",
"use logan_ir::{\n    graph::{Graph, Op, ValueType},",
"use logan_ir::{\n    ContextConstraint,\n    graph::{Graph, Op, ValueType},")
replace_once("logan-compiler/src/pipeline.rs",
"    pub optimization: OptimizationProfile,\n    pub dry_run: bool,",
"    pub optimization: OptimizationProfile,\n    /// Compile-time context intent. CLI callers must supply exactly one of\n    /// --max-context or --require-context.\n    pub context: Option<ContextConstraint>,\n    /// Enter hardware-specialized planning. Candidate search lands in #82;\n    /// until then this is rejected rather than silently behaving like a fixed quant.\n    pub optimize: bool,\n    pub dry_run: bool,")
replace_once("logan-compiler/src/pipeline.rs",
"            optimization: OptimizationProfile::Default,\n            dry_run: false,",
"            optimization: OptimizationProfile::Default,\n            context: None,\n            optimize: false,\n            dry_run: false,")
replace_once("logan-compiler/src/pipeline.rs",
"fn validate_supported_options(request: &CompileRequest) -> Result<()> {\n    match &request.quant {",
"fn validate_supported_options(request: &CompileRequest) -> Result<()> {\n    if request.optimize {\n        return Err(ColicError::unsupported(\n            Stage::TargetPlanning.as_str(),\n            \"--optimize is wired to the shared context contract, but mixed-representation Pareto search is not implemented yet (see #82); refusing to pretend a fixed quant is optimized\",\n        ));\n    }\n    match &request.quant {")

# recompile.rs: same request contract, native/auto target resolution, provenance.
replace_once("logan-compiler/src/recompile.rs", "use logan_format::{", "use logan_ir::ContextConstraint;\nuse logan_format::{")
replace_once("logan-compiler/src/recompile.rs",
"    pub codec: CodecMode,\n    pub allow_requantize: bool,",
"    pub codec: CodecMode,\n    /// Same context-planning contract as compile. Required by --optimize.\n    pub context: Option<ContextConstraint>,\n    /// Hardware-specialized optimizer entrypoint. The candidate search itself\n    /// is tracked in #82 and fails closed until it exists.\n    pub optimize: bool,\n    pub allow_requantize: bool,")
replace_once("logan-compiler/src/recompile.rs",
"            codec: CodecMode::Keep,\n            allow_requantize: false,",
"            codec: CodecMode::Keep,\n            context: None,\n            optimize: false,\n            allow_requantize: false,")
replace_once("logan-compiler/src/recompile.rs",
"pub fn recompile(request: &RecompileRequest) -> Result<RecompileSummary> {\n    if request.source == request.output && !request.force {",
"pub fn recompile(request: &RecompileRequest) -> Result<RecompileSummary> {\n    if request.optimize {\n        if request.context.is_none() {\n            return Err(ColicError::Usage(\n                \"recompile --optimize requires exactly one of --max-context N or --require-context N\".into(),\n            ));\n        }\n        return Err(ColicError::unsupported(\n            \"COLI optimization\",\n            \"--optimize is wired for recompile, including native target selection and context intent, but mixed-representation Pareto search is not implemented yet (see #82); no package was modified\",\n        ));\n    }\n    if request.source == request.output && !request.force {")
replace_once("logan-compiler/src/recompile.rs",
"fn resolve_target(package: &Package, requested: &str) -> Result<TargetProfile> {\n    let name = if requested == \"source\" {",
"fn resolve_target(package: &Package, requested: &str) -> Result<TargetProfile> {\n    if matches!(requested, \"auto\" | \"native\") {\n        return target::resolve(\n            &crate::pipeline::TargetRequest::Native,\n            &target::MachineProfile::probe(),\n        );\n    }\n    let name = if requested == \"source\" {")
replace_once("logan-compiler/src/recompile.rs",
"        \"quant_rules\": request.quant_rules.iter().map(|rule| rule.as_spec()).collect::<Vec<_>>(),\n        \"in_place\": request.source == request.output,",
"        \"quant_rules\": request.quant_rules.iter().map(|rule| rule.as_spec()).collect::<Vec<_>>(),\n        \"context\": request.context.map(|constraint| json!({\n            \"kind\": match constraint.kind {\n                logan_ir::ContextConstraintKind::Maximum => \"maximum\",\n                logan_ir::ContextConstraintKind::Required => \"required\",\n            },\n            \"tokens\": constraint.tokens,\n        })),\n        \"optimize\": request.optimize,\n        \"in_place\": request.source == request.output,")

# cli.rs: symmetric compile/recompile flags and validation.
replace_once("logan-compiler/src/cli.rs", "use std::path::PathBuf;\n\nuse crate::{", "use std::path::PathBuf;\n\nuse logan_ir::ContextConstraint;\n\nuse crate::{")
replace_once("logan-compiler/src/cli.rs",
"pub const USAGE: &str = \"Usage:\\n  logan inspect-source MODEL_DIR\\n  logan verify PACKAGE_DIR\\n  logan compile MODEL_DIR --target auto|native|PROFILE --quant exact|PROFILE --quant-floor bf16|exact --codec none|auto|PROFILE --opt default|size|latency -o OUTPUT [--plan PLAN_PATH] [--dry-run] [--verify] [--force]\\n  logan recompile PACKAGE_DIR (-o OUTPUT | --in-place) [--target source|PROFILE] [--quant keep|mxfp4] [--quant-rule SELECTOR=keep|mxfp4]... [--codec keep|none] [--allow-requantize] [--repack] [--verify] [--force]\";",
"pub const USAGE: &str = \"Usage:\\n  logan inspect-source MODEL_DIR\\n  logan verify PACKAGE_DIR\\n  logan compile MODEL_DIR (--max-context N | --require-context N) [--optimize] --target auto|native|PROFILE --quant exact|PROFILE --quant-floor bf16|exact --codec none|auto|PROFILE --opt default|size|latency -o OUTPUT [--plan PLAN_PATH] [--dry-run] [--verify] [--force]\\n  logan recompile PACKAGE_DIR (-o OUTPUT | --in-place) [--target source|auto|native|PROFILE] [--optimize (--max-context N | --require-context N)] [--quant keep|mxfp4] [--quant-rule SELECTOR=keep|mxfp4]... [--codec keep|none] [--allow-requantize] [--repack] [--verify] [--force]\";")
replace_once("logan-compiler/src/cli.rs",
"            \"--opt\" => {\n                request.optimization = OptimizationProfile::parse(&value(&mut args, \"--opt\")?)?;\n            }\n            \"--plan\" => request.plan = Some(PathBuf::from(value(&mut args, \"--plan\")?)),",
"            \"--opt\" => {\n                request.optimization = OptimizationProfile::parse(&value(&mut args, \"--opt\")?)?;\n            }\n            \"--optimize\" => request.optimize = true,\n            \"--max-context\" => {\n                if request.context.is_some() {\n                    return Err(ColicError::Usage(\n                        \"--max-context and --require-context are mutually exclusive\".into(),\n                    ));\n                }\n                request.context = Some(ContextConstraint::maximum(parse_context_tokens(\n                    &value(&mut args, \"--max-context\")?,\n                    \"--max-context\",\n                )?));\n            }\n            \"--require-context\" => {\n                if request.context.is_some() {\n                    return Err(ColicError::Usage(\n                        \"--max-context and --require-context are mutually exclusive\".into(),\n                    ));\n                }\n                request.context = Some(ContextConstraint::required(parse_context_tokens(\n                    &value(&mut args, \"--require-context\")?,\n                    \"--require-context\",\n                )?));\n            }\n            \"--plan\" => request.plan = Some(PathBuf::from(value(&mut args, \"--plan\")?)),")
replace_once("logan-compiler/src/cli.rs",
"    if !request.dry_run && request.output.is_none() {\n        return Err(ColicError::Usage(\n            \"compile requires -o/--output unless --dry-run is set\".into(),\n        ));\n    }\n    Ok(Command::Compile(request))",
"    if !request.dry_run && request.output.is_none() {\n        return Err(ColicError::Usage(\n            \"compile requires -o/--output unless --dry-run is set\".into(),\n        ));\n    }\n    if request.context.is_none() {\n        return Err(ColicError::Usage(\n            \"compile requires exactly one of --max-context N or --require-context N\".into(),\n        ));\n    }\n    Ok(Command::Compile(request))")
replace_once("logan-compiler/src/cli.rs", "fn parse_recompile<I>(args: I) -> Result<Command>\nwhere", "fn parse_context_tokens(value: &str, flag: &str) -> Result<u64> {\n    let tokens = value\n        .parse::<u64>()\n        .map_err(|_| ColicError::Usage(format!(\"{flag} must be a positive integer\")))?;\n    if tokens == 0 {\n        return Err(ColicError::Usage(format!(\"{flag} must be greater than zero\")));\n    }\n    Ok(tokens)\n}\n\nfn parse_recompile<I>(args: I) -> Result<Command>\nwhere")
replace_once("logan-compiler/src/cli.rs", "    let mut target = \"source\".to_owned();\n    let mut quant = RecompileQuantMode::Keep;", "    let mut target = \"source\".to_owned();\n    let mut target_explicit = false;\n    let mut context = None;\n    let mut optimize = false;\n    let mut quant = RecompileQuantMode::Keep;")
replace_once("logan-compiler/src/cli.rs",
"            \"--target\" => target = value(&mut args, \"--target\")?,\n            \"--quant\" => quant = RecompileQuantMode::parse(&value(&mut args, \"--quant\")?)?,",
"            \"--target\" => {\n                target = value(&mut args, \"--target\")?;\n                target_explicit = true;\n            }\n            \"--optimize\" => optimize = true,\n            \"--max-context\" => {\n                if context.is_some() {\n                    return Err(ColicError::Usage(\n                        \"--max-context and --require-context are mutually exclusive\".into(),\n                    ));\n                }\n                context = Some(ContextConstraint::maximum(parse_context_tokens(\n                    &value(&mut args, \"--max-context\")?,\n                    \"--max-context\",\n                )?));\n            }\n            \"--require-context\" => {\n                if context.is_some() {\n                    return Err(ColicError::Usage(\n                        \"--max-context and --require-context are mutually exclusive\".into(),\n                    ));\n                }\n                context = Some(ContextConstraint::required(parse_context_tokens(\n                    &value(&mut args, \"--require-context\")?,\n                    \"--require-context\",\n                )?));\n            }\n            \"--quant\" => quant = RecompileQuantMode::parse(&value(&mut args, \"--quant\")?)?,")
replace_once("logan-compiler/src/cli.rs", "    if in_place && output.is_some() {", "    if optimize && context.is_none() {\n        return Err(ColicError::Usage(\n            \"recompile --optimize requires exactly one of --max-context N or --require-context N\".into(),\n        ));\n    }\n    if !optimize && context.is_some() {\n        return Err(ColicError::Usage(\n            \"recompile context options require --optimize so they cannot be silently ignored\".into(),\n        ));\n    }\n    if optimize && !target_explicit {\n        target = \"auto\".to_owned();\n    }\n\n    if in_place && output.is_some() {")
replace_once("logan-compiler/src/cli.rs", "        codec,\n        allow_requantize,", "        codec,\n        context,\n        optimize,\n        allow_requantize,")
replace_once("logan-compiler/src/cli.rs", "                \"--opt\", \"latency\", \"-o\", \"out.coli\", \"--verify\",", "                \"--opt\", \"latency\", \"--max-context\", \"65536\", \"-o\", \"out.coli\", \"--verify\",")
replace_once("logan-compiler/src/cli.rs", "        assert_eq!(request.optimization, OptimizationProfile::Latency);\n        assert!(request.verify);", "        assert_eq!(request.optimization, OptimizationProfile::Latency);\n        assert_eq!(request.context, Some(ContextConstraint::maximum(65_536)));\n        assert!(request.verify);")
replace_once("logan-compiler/src/cli.rs", "    #[test]\n    fn recompile_rejects_output_with_in_place() {", "    #[test]\n    fn parses_optimized_recompile_with_same_context_contract() {\n        let command = parse([\n            \"recompile\", \"model.coli\", \"--in-place\", \"--optimize\",\n            \"--require-context\", \"131072\",\n        ].map(str::to_owned)).unwrap();\n        let Command::Recompile(request) = command else { panic!(\"expected recompile\") };\n        assert!(request.optimize);\n        assert_eq!(request.target, \"auto\");\n        assert_eq!(request.context, Some(ContextConstraint::required(131_072)));\n    }\n\n    #[test]\n    fn compile_and_recompile_reject_ambiguous_context_constraints() {\n        assert!(parse([\n            \"compile\", \"fixture\", \"--max-context\", \"32768\",\n            \"--require-context\", \"65536\", \"--dry-run\",\n        ].map(str::to_owned)).is_err());\n        assert!(parse([\n            \"recompile\", \"model.coli\", \"--in-place\", \"--optimize\",\n            \"--max-context\", \"32768\", \"--require-context\", \"65536\",\n        ].map(str::to_owned)).is_err());\n    }\n\n    #[test]\n    fn optimized_recompile_requires_context() {\n        assert!(parse([\"recompile\", \"model.coli\", \"--in-place\", \"--optimize\"].map(str::to_owned)).is_err());\n    }\n\n    #[test]\n    fn recompile_rejects_output_with_in_place() {")

print("symmetric context CLI wiring applied")
